import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Script from 'next/script';
import Navbar from '../components/navbar/navbar';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Script
        src='https://kit.fontawesome.com/2c36e9b7b1.js'
        crossOrigin='anonymous'
      />
      <Navbar />
      <p className='title'>
        <Link href='/posts/first-post'>Read More about me</Link>
      </p>
    </>
  );
}
