import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import '../styles/Home.module.css';
import Link from 'next/link';
import Script from 'next/script';
import Navbar from '../components/navbar/navbar';
import Maintop from '../components/maintop/maintop';
import Gallery from '../components/gallery/gallery';
import Coinbase from '../components/coinbase/coinbase';
import Jokes from '../components/jokes/jokes';

const inter = Inter({ subsets: ['latin'] });
export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Script
        src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'
        integrity='sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW'
        crossorigin='anonymous'
      />

      <Navbar />
      <Maintop />
      <Gallery />
      <div className='container-axios'>
        <Coinbase />
        <Jokes />
      </div>
      <p className='title'>
        <Link href='/posts/first-post'>Read More about me</Link>
      </p>
    </>
  );
}
